'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import CreatorUsername from './creator-username';
import type {UserRole} from '../../lib/roles';

type Announcement={id:string;title:string;summary:string;content:string;imageUrl:string|null;isGif:boolean;isPinned:boolean;isLocked:boolean;reactionCount:number;replyCount:number;createdAt:number;updatedAt:number;author:{displayName:string;username:string;role:UserRole;creatorRank:string;avatarUrl:string}};
export default function AnnouncementDetail({announcement:initial,canManage}:{announcement:Announcement;canManage:boolean}){
 const router=useRouter();const [item,setItem]=useState(initial);const [menu,setMenu]=useState(false);const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [title,setTitle]=useState(item.title);const [summary,setSummary]=useState(item.summary);const [content,setContent]=useState(item.content);
 async function patch(values:Record<string,unknown>){setBusy(true);const res=await fetch(`/api/discussions/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});setBusy(false);if(!res.ok){alert((await res.json()).error||'Could not update announcement');return false}setItem(v=>({...v,...values}));router.refresh();return true}
 async function save(){if(await patch({title,summary,content,isPinned:item.isPinned}))setEditing(false)}
 async function remove(){if(!confirm('Delete announcement? This action cannot be undone.'))return;setBusy(true);const res=await fetch(`/api/discussions/${item.id}`,{method:'DELETE'});if(res.ok)router.push('/discussion');else{setBusy(false);alert('Could not delete announcement')}}
 const date=new Date(item.createdAt).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
 return <article className="announcementDetail shell">
  <header className="announcementHeader"><div className="announcementBadges"><span>OFFICIAL ANNOUNCEMENT</span>{item.isPinned&&<span>PINNED</span>}{item.isLocked&&<span>READ ONLY</span>}</div>{canManage&&<div className="announcementManagement"><button type="button" onClick={()=>setEditing(true)}>Edit</button><button type="button" aria-label="Announcement actions" aria-expanded={menu} onClick={()=>setMenu(!menu)}>⋯</button>{menu&&<div className="announcementMenu"><button onClick={()=>{setEditing(true);setMenu(false)}}>Edit announcement</button><button disabled={busy} onClick={()=>patch({isPinned:!item.isPinned})}>{item.isPinned?'Unpin':'Pin'}</button><button disabled={busy} onClick={()=>patch({isLocked:!item.isLocked})}>{item.isLocked?'Unlock':'Lock'}</button><button className="danger" disabled={busy} onClick={remove}>Delete</button></div>}</div>}</header>
  <h1>{item.title}</h1><div className="announcementAuthor">{item.author.avatarUrl?<img src={item.author.avatarUrl} alt=""/>:<span>{item.author.displayName.slice(0,1)}</span>}<div><CreatorUsername name={item.author.displayName} username={item.author.username} creatorRank={item.author.creatorRank} staffRole={item.author.role}/><small>{date}{item.updatedAt>item.createdAt+1000?' · Edited':''}</small></div></div>
  {item.summary&&<p className="announcementSummary">{item.summary}</p>}<div className="announcementContent">{item.content.split('\n').map((p,i)=><p key={i}>{p}</p>)}</div>{item.imageUrl&&<div className="announcementMedia"><img src={item.imageUrl} alt=""/></div>}<footer className="announcementStats"><span>♡ {item.reactionCount}</span><span>Comments {item.replyCount}</span></footer>{item.isLocked&&<p className="announcementLocked">Replies are disabled for this announcement.</p>}
  {editing&&<div className="discussionModalOverlay" onClick={()=>setEditing(false)}><form className="announcementEdit" onClick={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();save()}}><div><p className="eyebrow">EDIT ANNOUNCEMENT</p><button type="button" onClick={()=>setEditing(false)} aria-label="Close">×</button></div><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={150}/></label><label>Short summary<input value={summary} onChange={e=>setSummary(e.target.value)} maxLength={300}/></label><label>Content<textarea value={content} onChange={e=>setContent(e.target.value)} required rows={10} maxLength={10000}/></label><label className="checkboxLabel"><input type="checkbox" checked={item.isPinned} onChange={e=>setItem(v=>({...v,isPinned:e.target.checked}))}/> Pin announcement</label><div className="formActions"><button type="button" className="button secondary" onClick={()=>setEditing(false)}>Cancel</button><button className="button" disabled={busy}>{busy?'Saving…':'Save changes'}</button></div></form></div>}
 </article>
}
