'use client';
import { useEffect,useState } from 'react';
import { readable } from '../../lib/staff-ui';
import { StaffEmpty,StaffError,StaffSkeleton } from './staff-states';
type Log={id:string;action:string;username?:string;target_username?:string;target_type:string;target_id:string;created_at:string;previous?:string;next?:string;reason?:string};
export default function AuditView({history=false}:{history?:boolean}) {
  const [filters,setFilters]=useState({action:'',actor:'',target:'',date:''}),[query,setQuery]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0);
  const [data,setData]=useState<{key:string;logs:Log[];hasMore:boolean;ownOnly:boolean}|null>(null),[error,setError]=useState('');
  const key=`${query}:${page}:${revision}:${history}`;
  useEffect(()=>{const controller=new AbortController();fetch(`/api/staff/audit?${query}&page=${page}${history?'&scope=moderation':''}`,{signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then(value=>setData({...value,key})).catch(()=>{if(!controller.signal.aborted)setError(key);});return()=>controller.abort();},[query,page,history,key]);
  return <div><form className="staffFilters" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(new URLSearchParams(filters).toString());setRevision(v=>v+1);}}><div className="staffFilterFields">{(['action','actor','target','date'] as const).map(name=><label key={name}>{readable(name)}<input type={name==='date'?'date':'text'} value={filters[name]} maxLength={100} placeholder={name==='actor'?'Username':name==='target'?'Username or ID':'Any action'} onChange={e=>setFilters(current=>({...current,[name]:e.target.value}))}/></label>)}</div><div className="staffActions"><button className="staffPrimary">Apply filters</button><button type="button" onClick={()=>{setFilters({action:'',actor:'',target:'',date:''});setQuery('');setPage(1);}}>Clear</button></div></form>
    {history&&<p className="staffHint">Without Audit Log permission, moderation history is limited to your own actions.</p>}
    {error===key?<StaffError retry={()=>setRevision(v=>v+1)}/>:data?.key!==key?<StaffSkeleton rows={4}/>:!data.logs.length?<StaffEmpty title="No matching activity">No recorded actions match these filters.</StaffEmpty>:<><div className="staffAuditGrid">{data.logs.map(log=><article className="staffAuditCard" key={log.id}><header><b>{readable(log.action)}</b><time dateTime={log.created_at}>{new Date(log.created_at).toLocaleString()}</time></header><dl className="staffFacts"><div><dt>Actor</dt><dd>{log.username?`@${log.username}`:'System'}</dd></div><div><dt>Target</dt><dd>{log.target_username?`@${log.target_username}`:`${readable(log.target_type)} · ${log.target_id}`}</dd></div><div><dt>Previous → New</dt><dd>{log.previous||log.next?`${readable(log.previous||'Not recorded')} → ${readable(log.next||'Not recorded')}`:'Not recorded'}</dd></div><div><dt>Reason</dt><dd>{log.reason||'No reason recorded'}</dd></div></dl></article>)}</div><div className="staffPagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button disabled={!data.hasMore} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}
  </div>;
}
