'use client';
import Link from 'next/link';
import { useEffect,useRef,useState } from 'react';
import RoleBadge from './role-badge';
import ReportButton from './report-button';
import { requireClientAuth } from '../../lib/auth-path';
import type { UserRole } from '../../lib/roles';
type Comment={id:string;parentId:string|null;body:string;author:string;username:string;authorRole:UserRole;avatarUrl:string;reactionCount:number;replyCount:number;viewerLiked:boolean;createdAt:number;canDelete:boolean;edited:boolean;deleted:boolean;pinned:boolean;isCreator:boolean};
type Thread={items:Comment[];page:number;hasMore:boolean;open:boolean};
function relativeTime(value:number){const minutes=Math.max(0,Math.floor((Date.now()-value)/60000));return minutes<1?'now':minutes<60?`${minutes}m`:minutes<1440?`${Math.floor(minutes/60)}h`:`${Math.floor(minutes/1440)}d`;}
export default function CommentConversation({postId,signedIn,canPin,review,total}:{postId:string;signedIn:boolean;canPin:boolean;review:{hide:boolean;delete:boolean}|null;total:number}){
  const [comments,setComments]=useState<Comment[]>([]),[threads,setThreads]=useState<Record<string,Thread>>({}),[count,setCount]=useState(total),[sort,setSort]=useState('relevant'),[page,setPage]=useState(1),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
  const [text,setText]=useState(''),[reply,setReply]=useState<Comment|null>(null),[editing,setEditing]=useState<Comment|null>(null),[editText,setEditText]=useState(''),[menu,setMenu]=useState<string|null>(null),[mention,setMention]=useState(''),[suggestions,setSuggestions]=useState<{username:string;display_name:string}[]>([]);
  const composer=useRef<HTMLTextAreaElement>(null),root=useRef<HTMLElement>(null);
  const endpoint=`/api/posts/${postId}/comments`;
  useEffect(()=>{const controller=new AbortController();fetch(`${endpoint}?sort=${sort}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error();return response.json();}).then(data=>{setComments(data.comments);setPage(1);setMore(data.hasMore);}).catch(()=>{if(!controller.signal.aborted)setMessage('Could not load comments. Please retry.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[endpoint,sort,revision]);
  useEffect(()=>{if(!mention)return;const controller=new AbortController();const timer=setTimeout(()=>{fetch(`/api/search?type=people&suggest=1&q=${encodeURIComponent(mention)}`,{signal:controller.signal}).then(response=>response.ok?response.json():{people:[]}).then(data=>setSuggestions(data.people||[])).catch(()=>{});},250);return()=>{clearTimeout(timer);controller.abort();};},[mention]);
  useEffect(()=>{if(!menu)return;const close=(event:Event)=>{if(event instanceof KeyboardEvent&&event.key==='Escape'||event instanceof PointerEvent&&!(event.target as Element).closest('.conversationMenu'))setMenu(null);};document.addEventListener('pointerdown',close);document.addEventListener('keydown',close);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',close);};},[menu]);
  const requireAuth=()=>requireClientAuth(signedIn,`/shots/${postId}#comments`,'Sign in to join the conversation');
  function updateComment(id:string,update:(comment:Comment)=>Comment){setComments(current=>current.map(item=>item.id===id?update(item):item));setThreads(current=>Object.fromEntries(Object.entries(current).map(([key,thread])=>[key,{...thread,items:thread.items.map(item=>item.id===id?update(item):item)}])));}
  async function like(comment:Comment){if(!requireAuth()||busy)return;setBusy(comment.id);updateComment(comment.id,item=>({...item,viewerLiked:!comment.viewerLiked,reactionCount:Math.max(0,comment.reactionCount+(comment.viewerLiked?-1:1))}));try{const response=await fetch(`${endpoint}/${comment.id}/react`,{method:'POST'});if(!response.ok)throw Error();const data=await response.json();updateComment(comment.id,item=>({...item,viewerLiked:data.liked,reactionCount:Math.max(0,comment.reactionCount+(data.liked===comment.viewerLiked?0:data.liked?1:-1))}));}catch{updateComment(comment.id,()=>comment);setMessage('Could not save the like. Please try again.');}finally{setBusy('');}}
  async function load(parent?:string,nextPage=1){setBusy(parent||'more');try{const response=await fetch(`${endpoint}?sort=${sort}&page=${nextPage}${parent?'&parent='+encodeURIComponent(parent):''}`);if(!response.ok)throw Error();const data=await response.json();if(parent)setThreads(current=>({...current,[parent]:{items:nextPage===1?data.comments:[...(current[parent]?.items||[]),...data.comments],page:nextPage,hasMore:data.hasMore,open:true}}));else{setComments(current=>[...current,...data.comments]);setPage(nextPage);setMore(data.hasMore);}}catch{setMessage('Could not load more comments.');}finally{setBusy('');}}
  async function submit(){if(!requireAuth()||busy)return;setBusy('submit');setMessage('Checking your comment…');try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:text,parentId:reply?.parentId||reply?.id||null})});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not post.');if(data.parentId){setThreads(current=>({...current,[data.parentId]:{items:[...(current[data.parentId]?.items||[]),data],page:current[data.parentId]?.page||1,hasMore:current[data.parentId]?.hasMore||!current[data.parentId],open:true}}));updateComment(data.parentId,item=>({...item,replyCount:(item.replyCount||0)+1}));}else setComments(current=>[data,...current]);setCount(value=>value+1);setText('');setReply(null);setMention('');if(data.parentId)await load(data.parentId,1);setMessage('Comment posted.');}catch(error){setMessage(error instanceof Error?error.message:'Network error. Your comment has been kept.');}finally{setBusy('');}}
  async function remove(comment:Comment){if(!confirm('Delete this comment? Existing replies will remain.'))return;setBusy(comment.id);try{const response=await fetch(`${endpoint}?commentId=${comment.id}`,{method:'DELETE'});if(!response.ok)throw Error();updateComment(comment.id,item=>({...item,deleted:true,body:'This comment was deleted.'}));setCount(value=>Math.max(0,value-1));setMenu(null);}catch{setMessage('Could not delete the comment.');}finally{setBusy('');}}
  async function saveEdit(){if(!editing)return;setBusy(editing.id);try{const response=await fetch(`${endpoint}?commentId=${editing.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:editText})});const data=await response.json();if(!response.ok)throw Error(data.error);updateComment(editing.id,item=>({...item,body:data.body,edited:true}));setEditing(null);}catch(error){setMessage(error instanceof Error?error.message:'Could not save your edit.');}finally{setBusy('');}}
  async function pin(comment:Comment){setBusy(comment.id);try{const response=await fetch(endpoint+'/pin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commentId:comment.pinned?null:comment.id})});if(!response.ok)throw Error();setRevision(value=>value+1);setMenu(null);}catch{setMessage('You cannot pin that comment.');}finally{setBusy('');}}
  async function moderate(comment:Comment,action:'REVIEW'|'HIDE'|'DELETE'){
    const reason=action==='REVIEW'?'':prompt(`${action==='HIDE'?'Hide':'Delete'} this comment — reason:`)?.trim();
    if(action!=='REVIEW'&&!reason)return;
    if(action==='DELETE'&&!confirm('Delete this comment for moderation? Its text will no longer be public.'))return;
    setBusy(comment.id);
    try{
      const response=await fetch(`${endpoint}/${comment.id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,reason})});
      const data=await response.json();if(!response.ok)throw Error(data.error||'Could not complete the review.');
      setMenu(null);
      if(action==='REVIEW')window.location.assign(data.url);
      else {updateComment(comment.id,item=>({...item,deleted:true,body:'This comment is unavailable.'}));setMessage(action==='HIDE'?'Comment hidden and case recorded.':'Comment deleted and case recorded.');}
    }catch(error){setMessage(error instanceof Error?error.message:'Could not complete the review.');}finally{setBusy('');}
  }
  function renderComment(comment:Comment,isReply=false){return <article className={'conversationComment'+(isReply?' conversationReply':'')} id={`comment-${comment.id}`} key={comment.id}>
<Link className="conversationAvatar" href={`/users/${comment.username}`} aria-label={`View ${comment.author}'s profile`}>{comment.avatarUrl?<img src={comment.avatarUrl} alt="" width={34} height={34} loading="lazy"/>:comment.author.slice(0,1)}</Link><div className="conversationBody"><header><Link href={`/users/${comment.username}`}>{comment.author}</Link><RoleBadge role={comment.authorRole}/>{comment.isCreator&&<small>Creator</small>}{comment.pinned&&<small>⌖ Pinned</small>}<div className="conversationMenu"><button aria-label={`Actions for ${comment.author}'s comment`} aria-expanded={menu===comment.id} onClick={()=>setMenu(menu===comment.id?null:comment.id)}>⋯</button>{menu===comment.id&&<div>{comment.canDelete&&!comment.deleted&&<><button onClick={()=>{setEditing(comment);setEditText(comment.body);setMenu(null);}}>Edit</button><button onClick={()=>remove(comment)}>Delete</button></>}{!comment.deleted&&<ReportButton targetType="COMMENT" targetId={comment.id}/>} {review&&!comment.deleted&&<><button onClick={()=>moderate(comment,'REVIEW')}>Review details</button>{review.hide&&<button onClick={()=>moderate(comment,'HIDE')}>Hide</button>}{review.delete&&<button onClick={()=>moderate(comment,'DELETE')}>Delete as staff</button>}</>} {!isReply&&canPin&&!comment.deleted&&<button onClick={()=>pin(comment)}>{comment.pinned?'Unpin':'Pin comment'}</button>}</div>}</div></header>
    {editing?.id===comment.id?<form onSubmit={event=>{event.preventDefault();saveEdit();}}><textarea aria-label="Edit comment" value={editText} onChange={event=>setEditText(event.target.value)} required maxLength={1000}/><button disabled={!!busy}>Save</button><button type="button" onClick={()=>setEditing(null)}>Cancel</button></form>:<p>{comment.body.split(/(@[a-z0-9][a-z0-9_-]{1,29})/gi).map((part,index)=>part.startsWith('@')?<Link key={index} href={`/users/${part.slice(1)}`}>{part}</Link>:part)}{comment.edited&&!comment.deleted&&<small> · Edited</small>}</p>}
    <div className="conversationActions">{!comment.deleted&&<><button disabled={!!busy} aria-pressed={comment.viewerLiked} onClick={()=>like(comment)}>{comment.viewerLiked?'♥':'♡'} {comment.reactionCount||0}</button><button onClick={()=>{if(requireAuth()){setReply(comment);composer.current?.focus();}}}>Reply</button></>}<time dateTime={new Date(comment.createdAt).toISOString()} title={new Date(comment.createdAt).toLocaleString()}>{relativeTime(comment.createdAt)}</time></div>
    {!isReply&&(comment.replyCount>0||threads[comment.id]?.items.length>0)&&<><button className="viewReplies" disabled={!!busy} aria-expanded={threads[comment.id]?.open||false} onClick={()=>{if(threads[comment.id])setThreads(current=>({...current,[comment.id]:{...current[comment.id],open:!current[comment.id].open}}));else load(comment.id);}}>{threads[comment.id]?.open?'Hide replies':`View ${comment.replyCount||threads[comment.id]?.items.length} replies`}</button>{threads[comment.id]?.open&&<>{threads[comment.id].items.map(item=>renderComment(item,true))}{threads[comment.id].hasMore&&<button disabled={!!busy} onClick={()=>load(comment.id,threads[comment.id].page+1)}>Load more replies</button>}</>}</>}
    </div></article>;}
return <section ref={root} className="commentsSection conversation" id="comments"><div className="commentsHeading"><h2>Comments <span>{count}</span></h2><label>Sort <select value={sort} onChange={event=>{setLoading(true);setSort(event.target.value);}}><option value="relevant">Most relevant</option><option value="newest">Newest</option><option value="oldest">Oldest</option></select></label></div>{loading?<p>Loading comments…</p>:comments.length?comments.map(item=>renderComment(item)):<p>No comments yet. Start the conversation.</p>}{more&&<button disabled={!!busy} onClick={()=>load(undefined,page+1)}>Load more comments</button>}
    <form className="commentForm" onSubmit={event=>{event.preventDefault();submit();}}>{reply&&<div className="replyContext">Replying to {reply.author}<button type="button" aria-label="Cancel reply" onClick={()=>setReply(null)}>×</button></div>}<textarea ref={composer} id="comment-composer" value={text} maxLength={1000} required placeholder={reply?'Write a reply…':'Add a comment…'} onFocus={()=>requireAuth()} onChange={event=>{setText(event.target.value);const match=event.target.value.slice(0,event.target.selectionStart).match(/(?:^|\s)@([\w-]{1,30})$/);setMention(match?.[1]||'');setSuggestions([]);}}/>
      {mention&&suggestions.length>0&&<div className="mentionSuggestions" aria-label="Mention suggestions">{suggestions.map(person=><button type="button" key={person.username} onClick={()=>{const position=composer.current?.selectionStart||text.length;const before=text.slice(0,position).replace(/@[\w-]+$/,'@'+person.username+' ');setText(before+text.slice(position));setMention('');composer.current?.focus();}}>{person.display_name} <small>@{person.username}</small></button>)}</div>}<div><small>{text.length}/1000</small><button className="primary" disabled={!!busy||!text.trim()}>{busy==='submit'?'Checking…':reply?'Reply':'Post'}</button></div></form><p role="status" aria-live="polite">{message}</p></section>;
}
