'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { useStaff } from './staff-shell';
import type { TrustedConfig } from '../../lib/trusted-policy';
type Application={id:string;user_id:string;display_name:string;username:string;role:string;status:string;kind:string;reason:string;contribution:string;content_types:string;portfolio_url:string;version:number;created_at:string;account_days:number;published_posts:number;previously_removed:boolean};
export default function TrustedReview(){
  const user=useStaff();const [data,setData]=useState<{applications:Application[];config:TrustedConfig|null;hasMore:boolean}|null>(null),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[selected,setSelected]=useState<Application|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/staff/trusted-contributors?page=${page}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error('Could not load applications.');return response.json();}).then(setData).catch(error=>{if(!controller.signal.aborted)setMessage(error.message);});return()=>controller.abort();},[page,revision]);
  async function review(body:Record<string,unknown>){setBusy(true);setMessage('');try{const response=await fetch('/api/staff/trusted-contributors',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error);setSelected(null);setRevision(value=>value+1);setMessage('Review saved.');}catch(error){setMessage(error instanceof Error?error.message:'Network error.');}finally{setBusy(false);}}
  return <section className="staffSection"><h2>Trusted Contributors</h2><p role="status">{message}</p>{!data?<p>Loading applications…</p>:<>
    {data.config&&<details><summary>Eligibility configuration</summary><form className="settingsForm" onSubmit={event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const config=Object.fromEntries(Object.entries(values).map(([key,value])=>[key,key==='appealsEnabled'?value==='true':Number(value)]));review({action:'CONFIGURE',config});}}>{Object.entries(data.config).map(([key,value])=><label key={key}>{({accountDays:'Minimum account age (days)',posts:'Minimum Skillshots',participation:'Minimum constructive comments',rejectionDays:'Reapplication cooldown (days)',appealDays:'Appeal cooldown (days)',violationDays:'Recent moderation history window (days)',appealsEnabled:'Allow appeals'} as Record<string,string>)[key]}{typeof value==='boolean'?<select name={key} defaultValue={String(value)}><option value="true">Yes</option><option value="false">No</option></select>:<input name={key} type="number" min={0} max={3650} defaultValue={value} required/>}</label>)}<button disabled={busy}>Save requirements</button></form></details>}
    {!data.applications.length?<p>No applications yet.</p>:<div className="staffTable">{data.applications.map(item=><article key={item.id}><div><b>{item.display_name}</b><small>{item.kind} · {item.status} · {new Date(item.created_at).toLocaleDateString()}</small></div><button onClick={()=>setSelected(item)}>Review</button></article>)}</div>}
    <div className="settingsActions"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {page}</span><button disabled={!data.hasMore} onClick={()=>setPage(value=>value+1)}>Next</button></div>
    {selected&&<section className="settingsSection"><button onClick={()=>setSelected(null)}>Close review</button><h3>{selected.display_name} · @{selected.username}</h3><Link href={`/users/${selected.username}`}>Open profile →</Link><p>Current role: {selected.role}. Account age: {selected.account_days} days. Published Skillshots: {selected.published_posts}. Previously removed: {selected.previously_removed?'Yes':'No'}.</p><h4>Application answers</h4><p>{selected.reason}</p><p>{selected.contribution}</p><p>{selected.content_types}</p>{/^https?:\/\//.test(selected.portfolio_url)&&<a href={selected.portfolio_url} target="_blank" rel="noopener noreferrer">Portfolio ↗</a>}
      {['PENDING','UNDER_REVIEW','MORE_INFO','SUSPENDED'].includes(selected.status)&&<form className="settingsForm" onSubmit={event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));if(confirm('Save this application decision?'))review({...values,applicationId:selected.id,version:selected.version});}}><label>Action<select name="action"><option value="REVIEW">Mark under review</option><option value="MORE_INFO">Request more information</option>{user.permissions.includes('trusted_contributor.approve')&&<option value="APPROVE">{selected.kind==='APPEAL'?'Approve appeal':'Approve & grant role'}</option>}{user.permissions.includes('trusted_contributor.reject')&&<><option value="REJECT">{selected.kind==='APPEAL'?'Uphold / reject appeal':'Reject'}</option><option value="SUSPEND">Suspend application</option><option value="DISMISS">Dismiss</option></>}</select></label><label>Internal review reason<textarea name="note" required minLength={5} maxLength={2000}/></label><label>Message to applicant (optional)<textarea name="publicNote" maxLength={1000}/></label><button disabled={busy}>Save decision</button></form>}
      {selected.role==='TRUSTED_CONTRIBUTOR'&&user.permissions.includes('trusted_contributor.revoke')&&<button disabled={busy} onClick={()=>{const note=prompt('Reason for removing Trusted Contributor status (private):');if(note&&confirm('Remove this user’s Trusted Contributor role?'))review({action:'REVOKE',userId:selected.user_id,note});}}>Remove Trusted Contributor status</button>}
    </section>}
  </>}</section>;
}
