'use client';
import { useState } from 'react';
import { canModerateUser,type UserRole,type Permission } from '../../lib/roles';
import { useStaff } from './staff-shell';
import StaffDialog from './staff-dialog';
import RoleBadge from './role-badge';
import { StaffEmpty,StaffStatus } from './staff-states';
type User={id:string;display_name:string;username:string;role:UserRole;status:string;created_at:string};
export default function UserManager(){
  const principal=useStaff();
  const [users,setUsers]=useState<User[]>([]),[q,setQ]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[searched,setSearched]=useState(false);
  const [pending,setPending]=useState<{user:User;action:string}|null>(null);
  async function search(){setBusy(true);setMessage('');try{const response=await fetch(`/api/staff/users?q=${encodeURIComponent(q)}`);if(!response.ok)throw new Error();setUsers((await response.json()).users);setSearched(true);}catch{setMessage('Something went wrong. Please try searching again.');}finally{setBusy(false);}}
  async function act(){if(!pending)return;setBusy(true);try{const response=await fetch('/api/staff/users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({userId:pending.user.id,action:pending.action})});if(!response.ok)throw new Error();setPending(null);await search();setMessage('Account status updated.');}catch{setMessage('Could not update this account. Check your access and try again.');}finally{setBusy(false);}}
  const actions=(user:User)=>user.id===principal.id||!canModerateUser(principal.role,user.role)?[]:(user.status==='ACTIVE'?['SUSPEND','BAN']:user.status==='BANNED'?['UNBAN']:['UNSUSPEND']).filter(action=>principal.permissions.includes(`users.${action.toLowerCase()}` as Permission));
  return <section className="staffSection"><form className="teamSearch" onSubmit={e=>{e.preventDefault();search();}}><label className="staffSearchLabel">Find a community account<input value={q} maxLength={50} onChange={e=>setQ(e.target.value)} placeholder="Display name or @username" required/></label><button className="staffPrimary" disabled={busy}>{busy?'Searching…':'Search'}</button></form><div className="staffTable">{users.map(user=><article key={user.id}><div><b>{user.display_name} <RoleBadge role={user.role}/></b><span>@{user.username}</span><small>Joined {new Date(user.created_at).toLocaleDateString()}</small><StaffStatus value={user.status}/></div><div>{actions(user).map(action=><button key={action} disabled={busy} className={action==='BAN'?'staffDanger':''} onClick={()=>setPending({user,action})}>{action==='UNSUSPEND'?'Restore':action.toLowerCase()}</button>)}</div></article>)}</div>{!users.length&&<StaffEmpty title={searched?'No matching users':'Find an account'}>{searched?'Try another display name or username.':'Search for an account to manage it.'}</StaffEmpty>}<p role="status">{message}</p>{pending&&<StaffDialog title={`${pending.action.toLowerCase()} @${pending.user.username}?`} onClose={()=>{if(!busy)setPending(null);}}><p>This changes the account’s access to Skillshot. The action is recorded in the audit log.</p><div className="staffActions"><button disabled={busy} onClick={()=>setPending(null)}>Cancel</button><button className="staffDanger" disabled={busy} onClick={act}>{busy?'Saving…':'Confirm change'}</button></div><p role="status">{message}</p></StaffDialog>}</section>;
}
